// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCaWFlHNq_8hF9dIOhpYeKQiJV3RT9iA',
    appId: '1:128853313339:web:af993d528194f88df8191e',
    messagingSenderId: '128853313339',
    projectId: 'paper-generator-54ef6',
    authDomain: 'paper-generator-54ef6.firebaseapp.com',
    storageBucket: 'paper-generator-54ef6.firebasestorage.app',
    measurementId: 'G-DVWL4RVWKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVKsimJnKlFJNdtYIbqnVlLcvQi_nzcQo',
    appId: '1:128853313339:android:c26f44af45e962faf8191e',
    messagingSenderId: '128853313339',
    projectId: 'paper-generator-54ef6',
    storageBucket: 'paper-generator-54ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Dx4JV_3O1zyWsUwLZVMKFC4QfpHUaRA',
    appId: '1:128853313339:ios:0787a8d06333fec3f8191e',
    messagingSenderId: '128853313339',
    projectId: 'paper-generator-54ef6',
    storageBucket: 'paper-generator-54ef6.firebasestorage.app',
    androidClientId: '128853313339-5ecqum3jhur8vp3v0tnv81luor3dmtcj.apps.googleusercontent.com',
    iosClientId: '128853313339-5ke7jvn2nf98adtvmovthopj9dtjj2ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperGenarateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Dx4JV_3O1zyWsUwLZVMKFC4QfpHUaRA',
    appId: '1:128853313339:ios:0787a8d06333fec3f8191e',
    messagingSenderId: '128853313339',
    projectId: 'paper-generator-54ef6',
    storageBucket: 'paper-generator-54ef6.firebasestorage.app',
    androidClientId: '128853313339-5ecqum3jhur8vp3v0tnv81luor3dmtcj.apps.googleusercontent.com',
    iosClientId: '128853313339-5ke7jvn2nf98adtvmovthopj9dtjj2ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperGenarateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtCaWFlHNq_8hF9dIOhpYeKQiJV3RT9iA',
    appId: '1:128853313339:web:28d5041d9d516545f8191e',
    messagingSenderId: '128853313339',
    projectId: 'paper-generator-54ef6',
    authDomain: 'paper-generator-54ef6.firebaseapp.com',
    storageBucket: 'paper-generator-54ef6.firebasestorage.app',
    measurementId: 'G-P9M191SZYQ',
  );

}